/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiEditor: typeof import('./src/components/AiEditor.vue')['default']
    DataCard: typeof import('./src/components/DataCard.vue')['default']
    ResumeSection: typeof import('./src/components/ResumeSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowCard: typeof import('./src/components/ShowCard.vue')['default']
    ThemeIcon: typeof import('./src/components/ThemeIcon.vue')['default']
  }
}
