/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiEditor: typeof import('./src/components/AiEditor.vue')['default']
    DataCard: typeof import('./src/components/DataCard.vue')['default']
    ImgDrawer: typeof import('./src/components/ImgDrawer.vue')['default']
    PhotoImg: typeof import('./src/components/PhotoImg.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeIcon: typeof import('./src/components/ThemeIcon.vue')['default']
  }
}
